# The deployment section should be excluded until
# it is explicitly included in module 5

#deployment:
#  dockerhub:
#    branch: master
#    commands:
#      - $DOCKER_HUB_TRIGGER
#
#
version: 2
jobs:
  build:
    environment:
      IMAGE_NAME: musibs/docker_auto_ci
    docker:
      - image: musibs/docker_auto_ci
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker Image
          command: docker build -t $IMAGE_NAME:latest
      - run: npm install
      - run: npm install supertest --save-dev
      - run: mkdir ~/junit
      - run:
          command: npm run test
          environment:
            MOCHA_FILE: ~/junit/test-results.xml
          when: always
      - store_test_results:
          path: ~/junit
      - store_artifacts:
          path: ~/junit 
workflows:
  version: 2
  build-master:
    jobs:
      - build:
          filters:
            branches:
              only: master

